### ISSUE TITLE
Remove underscore from list of suggestions

### ISSUE THREAD

**Issue by JasonFritsche** [tjrawrin/vue-times#25]
The list of suggestions currently does not remove underscores from cities. For example, if you search for the term "san" you will see the list below.
![unformatted_suggestions](https://user-images.githubusercontent.com/34847680/135733543-e3f3e983-3e1a-4da8-a9ce-791fbe1117cd.png)

Here you can see three names with underscores in their name. I am proposing that the underscore be replaced with a space.

**Comment by tjrawrin** [comment]
Thanks for the enhancement!
